### ISSUE TITLE
Permissions page not responsive to screen/display sizes

### ISSUE THREAD

**Issue by rayhua12** [bcgov/BCVAX-Android#26]
For particularly small or older phones, the default "display size", as defined in device settings (Display -> Display Size), causes the blue button to accept camera permissions to be off screen. Without pressing this button, even setting the camera permissions in device App Settings does not allow access to the app. 

**Workaround:** On this particular device, setting the "display size" to "small" decreases the display size enough to press the accept permissions button. 

**Version:** Android 9

**Device:** Nokia TA-1079

**Display resolution:**  854 x 480

**App Version:** 1.0

**Comment by pinakinkansara** [comment]
Thank you for the input.
We have resolved this issue. You can check out the latest open beta from the below link
[1.0.1](https://play.google.com/store/apps/details?id=ca.bc.gov.vaxcheck)

Kindly provided your feedback post update.
