### ISSUE TITLE
Publish app on Fdroid

### ISSUE THREAD

**Issue by charsi** [bcgov/BCVAX-Android#31]
Hello, would it be okay for this app to be added to Fdroid? 
I have created a request for this here - https://gitlab.com/fdroid/rfp/-/issues/1854

Fdroid seeks the app developer's consent before they include it on the app store.

**Comment by Altonss** [comment]
Any update on that topic? (maybe @pinakinkansara)

**Comment by IzzySoft** [comment]
The RFP at F-Droid is now entering candidate-to-close phase as there's no response – we cannot build it in its current state, as it comes with proprietary dependencies. So any chance you could work on this, @bcgovjz?

**Comment by charsi** [comment]
Closing since this app is already not in use in BC anymore. So there is very little benefit in having it published on F-droid now.

**Comment by IzzySoft** [comment]
Thanks for clarity, @charsi – I've then closed the RFP at F-Droid as well.
